say_title ( "Koe-Pung:" ) 
say ( "" ) 
say ( "5 Milyon yang karþýlýðýnda sana" ) 
say ( "kan taþý verebilirim." ) 
say ( "" ) 
say ( "Satýn almak istiyor musun?" ) 
say ( "" ) 
local satin = select ( "Satýn al" , "Alma" ) 
if satin == 1 then 
local ucret = 5e+06 
if pc . money < ucret then 
say_title ( "Koe-Pung:" ) 
say ( "" ) 
say ( "Yeterli yangýn yok." ) 
say ( "" ) 
return 
else 
pc . changegold ( - ucret ) 
pc . give_item2 ( "30190" , 1 ) 
end 
end 
