import uiScriptLocale
window = {
	'name': 'RefineDialog',
	'style': ('movable', 'float'),
	'x': SCREEN_WIDTH - 400,
	'y': 56000 / SCREEN_HEIGHT,
	'width': 0,
	'height': 0,
	'children': 
	(
		{
			'name': 'Board',
			'type': 'board',
			'style': ('attach',),
			'x': 0,
			'y': 0,
			'width': 0,
			'height': 0,
			'children': 
			(
				{
					'name': 'TitleBar',
					'type': 'titlebar',
					'style': ('attach',),
					'x': 8,
					'y': 8,
					'width': 0,
					'color': 'red',
					'children': 
					(	
						{
							'name': 'TitleName',
							'type': 'text',
							'text': 'Efsun Ekle',
							'horizontal_align': 'center',
							'text_horizontal_align': 'center',
							'x': 0,
							'y': 3,
						},
					),
				},
				{
					'name': 'SelectBonusButton0',
					'type': 'button',
					'x': 0,
					'y': 150,
					'text': uiScriptLocale.OK,
					'horizontal_align': 'center',
					'vertical_align': 'bottom',
					'default_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'over_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'down_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
				},
				{	
					'name': 'SelectBonusButton1',
					'type': 'button',
					'x': 0,
					'y': 130,
					'text': uiScriptLocale.OK,
					'horizontal_align': 'center',
					'vertical_align': 'bottom',
					'default_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'over_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'down_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
				},
				{
					'name': 'SelectBonusButton2',
					'type': 'button',
					'x': 0,
					'y': 110,
					'text': uiScriptLocale.OK,
					'horizontal_align': 'center',
					'vertical_align': 'bottom',
					'default_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'over_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'down_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
				},
				{
					'name': 'SelectBonusButton3',
					'type': 'button',
					'x': 0,
					'y': 90,
					'text': uiScriptLocale.OK,
					'horizontal_align': 'center',
					'vertical_align': 'bottom',
					'default_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'over_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'down_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
				},
				{
					'name': 'SelectBonusButton4',
					'type': 'button',
					'x': 0,
					'y': 69,
					'text': uiScriptLocale.OK,
					'horizontal_align': 'center',
					'vertical_align': 'bottom',
					'default_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'over_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
					'down_image': 'd:/ymir work/ui/public/parameter_slot_05.sub',
				},
				{
					'name': 'Cost',
					'type': 'text',
					'text': 'Seçilen efsunlar eklensin mi?',
					'horizontal_align': 'center',
					'vertical_align': 'bottom',
					'text_horizontal_align': 'center',
					'x': 0,
					'y': 52,
				},
				{
					'name': 'AcceptButton',
					'type': 'button',
					'x': -35,
					'y': 35,
					'text': uiScriptLocale.OK,
					'horizontal_align': 'center',
					'vertical_align': 'bottom',
					'default_image': 'd:/ymir work/ui/public/Middle_Button_01.sub',
					'over_image': 'd:/ymir work/ui/public/Middle_Button_02.sub',
					'down_image': 'd:/ymir work/ui/public/Middle_Button_03.sub',
				},
				{
					'name': 'CancelButton',
					'type': 'button',
					'x': 35,
					'y': 35,
					'text': uiScriptLocale.CANCEL,
					'horizontal_align': 'center',
					'vertical_align': 'bottom',
					'default_image': 'd:/ymir work/ui/public/Middle_Button_01.sub',
					'over_image': 'd:/ymir work/ui/public/Middle_Button_02.sub',
					'down_image': 'd:/ymir work/ui/public/Middle_Button_03.sub',
				},
			),
		},
	),
}
